SECRET_KEY = "secret"
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = "jayborsaniya.softrefine@gmail.com"
MAIL_PASSWORD = "tjawfxxarwteltuf"
MAIL_DEFAULT_SENDER = ("jay", "jayborsaniya.softrefine@gmail.com")
MAIL_MAX_EMAILS = None
MAIL_ASCII_ATTACHMENTS = False
